/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_api_records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Corpus browse. Spec section 9. Lexical only -- no embeddings in Stage A.
         *
         *     Searches both the Arabic text and the (also indexed) English Pickthall
         *     translation -- see `_normalize_query` for why a purely-Arabic
         *     normalization used to make English queries return nothing.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corpus */
        get: operations["corpus_api_corpus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClaimOut */
        ClaimOut: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Note */
            note: string;
        };
        /** CorpusResponse */
        CorpusResponse: {
            /** Db Sha256 */
            db_sha256: string;
            /** Db Path */
            db_path: string;
            stats: components["schemas"]["CorpusStatsOut"];
            /** Scope */
            scope: string;
            /** Sources */
            sources: components["schemas"]["CorpusSourceOut"][];
        };
        /**
         * CorpusSourceOut
         * @description One row of `sources` -- mirrors its columns exactly (see
         *     `corpus.schema.AUDIT_SCHEMA_SQL`'s sibling, the corpus schema's `sources`
         *     table). This is the provenance panel's data: license, attribution, and
         *     the verbatim Tanzil notice. A field added to the table but not here would
         *     be silently dropped from every API response that lists sources -- the
         *     same "two things meant to agree, quietly diverging" failure this project
         *     keeps hitting, just moved into the response layer instead of the client.
         */
        CorpusSourceOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Publisher */
            publisher?: string | null;
            /** Edition */
            edition?: string | null;
            /** Url */
            url: string;
            /** License Id */
            license_id: string;
            /** License Url */
            license_url?: string | null;
            /** Attribution */
            attribution: string;
            /** Retrieved At */
            retrieved_at: string;
            /** Upstream Sha256 */
            upstream_sha256: string;
            /** Modifications */
            modifications: string;
        };
        /** CorpusStatsOut */
        CorpusStatsOut: {
            /** Records */
            records: number;
            /** Sources */
            sources: number;
            /** Translations */
            translations: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QuotationOut */
        QuotationOut: {
            /** Quoted Text */
            quoted_text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Verdict */
            verdict: string;
            /** Tier */
            tier: string | null;
            /** Score */
            score: number;
            record: components["schemas"]["RecordOut"] | null;
            /** Also At */
            also_at?: string[];
            /** Given Reference */
            given_reference: string | null;
            /** Diff */
            diff: [
                string,
                string
            ][] | null;
        };
        /**
         * RecordDetailOut
         * @description `GET /api/records/{id}`'s full response -- a superset of `RecordOut`
         *     (which is what `QuotationOut.record` embeds). This endpoint additionally
         *     surfaces the surah's bilingual name and the full source record, so it
         *     gets its own model rather than reusing `RecordOut`.
         */
        RecordDetailOut: {
            /** Id */
            id: string;
            /** Reference Display */
            reference_display: string;
            /** Text Ar */
            text_ar: string;
            /** Text Ar Sha256 */
            text_ar_sha256: string;
            /** Surah */
            surah?: number | null;
            /** Ayah */
            ayah?: number | null;
            /** Surah Name Ar */
            surah_name_ar?: string | null;
            /** Surah Name En */
            surah_name_en?: string | null;
            /** Translation En */
            translation_en?: string | null;
            /** Translation Disclaimer */
            translation_disclaimer?: string | null;
            source?: components["schemas"]["CorpusSourceOut"] | null;
        };
        /** RecordOut */
        RecordOut: {
            /** Id */
            id: string;
            /** Reference Display */
            reference_display: string;
            /** Text Ar */
            text_ar: string;
            /** Text Ar Sha256 */
            text_ar_sha256: string;
            /** Surah */
            surah?: number | null;
            /** Ayah */
            ayah?: number | null;
            /** Translation En */
            translation_en?: string | null;
            /** Translation Disclaimer */
            translation_disclaimer?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Text */
            text: string;
        };
        /** VerifyResponse */
        VerifyResponse: {
            /** Quotations */
            quotations: components["schemas"]["QuotationOut"][];
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Risk */
            risk: string;
            /** Requires Handoff */
            requires_handoff: boolean;
            /** Overall */
            overall: string;
            /** Corpus Scope */
            corpus_scope: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    verify_api_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corpus_api_corpus_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
